apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: tusharkansal/authentication:latest
          ports:
            - containerPort: 7000
          env:
            - name: API_HOST
              value: api-gateway-service
            - name: API_PORT
              value: "8000"
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRESS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password-secret
                  key: postgres-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: postgres-password-secret
                  key: jwt-secret