apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  labels:
    app: authentication
spec:
  selector:
    app: authentication
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000