apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspector
spec:
  containers:
  - image: arunvelsriram/utils
    name: pvc-inspector
    command: ["sh" ,"-c" , "sleep infinity"]
    #args: ["-f", "/dev/null"]
  #   volumeMounts:
  #   - mountPath: /pvc
  #     name: pvc-mount
  # volumes:
  # - name: pvc-mount
  #   persistentVolumeClaim:
  #     claimName: nextjs-client-pvc