apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspector
spec:
  containers:
  - image: node
    name: pvc-inspector
    command: ["sh" ,"-c" , "cd /pvc && npm install -D @swc/cli @swc/core && sleep infinity"]
    #args: ["-f", "/dev/null"]
    volumeMounts:
    - mountPath: /pvc
      name: pvc-mount
  volumes:
  - name: pvc-mount
    persistentVolumeClaim:
      claimName: nextjs-client-pvc