apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: tusharkansal/nextjs-dev:latest
          ports:
           - containerPort: 3000
          volumeMounts:
            - name: nextjs-source
              mountPath: /app
      volumes:
        - name: nextjs-source
          #hostPath:
            #path: "/run/desktop/mnt/host/c/projects/distributed-file-storage/nextjs-client"
          persistentVolumeClaim:
            claimName: nextjs-client-pvc