apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextjs-client-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Must match the access mode of the PV
  resources:
    requests:
      storage: 1Gi  # Request the same amount of storage as the PV
