apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: nextjs-dev:latest
          ports:
           - containerPort: 3000
          volumeMounts:
            - name: nextjs-source
              mountPath: /app
            - name: node-modules
              mountPath: /app/node_modules
      volumes:
        - name: nextjs-source
          hostPath:
            path: ../client
        - name: node-modules
          emptyDir: {}