apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: tusharkansal/nextjs-client:latest
          ports:
           - containerPort: 3000
          volumeMounts:
            - name: nextjs-source
              mountPath: /app
          env:
            - name: NEXT_PUBLIC_AUTH_API_HOST
              value: localhost #authentication-service (not working when giving the service name as host, getting name not resolved error!)
            - name: NEXT_PUBLIC_AUTH_API_PORT
              value: "7000"
      volumes:
        - name: nextjs-source
          hostPath:
            path: "/run/desktop/mnt/host/c/projects/distributed-file-storage/nextjs-client"
          # persistentVolumeClaim:
          #   claimName: nextjs-client-pvc